### ISSUE TITLE
Webpack bundling errors with 8.2.0

### ISSUE THREAD

**Issue by salv0** [HubSpot/hubspot-api-nodejs#284]
Hi there, 

I've updated to the latest version and bundling with Webpack returns the following errors (a single one for reference)

```
ERROR in ../../@hubspot/api-client/lib/src/discovery/BaseDiscovery.d.ts 3:10
Module parse failed: Unexpected token (3:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import IConfiguration from '../configuration/IConfiguration';
| export default class BaseDiscovery {
>     config: IConfiguration;
|     constructor(config?: IConfiguration);
| }
 @ ../../@hubspot/api-client/lib/src/discovery/ sync ^\.\/.*$ ./BaseDiscovery.d.ts ./BaseDiscovery.d
 @ ../../@hubspot/api-client/lib/src/services/initObject.js 5:26-57
 @ ../../@hubspot/api-client/lib/src/client.js 15:21-53
 @ ../../@hubspot/api-client/lib/index.js 4:15-38
```

I am not sure if this is due to some configuration on my side, but it just started appearing after I bumped to version 8.2.0 of the client (was previously quite behind on 6.0.1).

Any idea? Thanks in advance for the help!

**Comment by EugeneLuminaPain** [comment]
+1

Also getting webpack ^5 build errors on a build script that uses shared libraries which include hubspot/api ^8.
I read through #262 where the one resolver seems to be to ignore the d.ts & js.map files...

**Comment by ksvirkou-hubspot** [comment]
Hi 
Unfortunately, I can’t reproduce it.
Could anybody provide minimal webpack setup, please?

**Comment by EugeneLuminaPain** [comment]
> Hi Unfortunately, I can’t reproduce it. Could anybody provide minimal webpack setup, please?

Hi Ksvirkou

For my instance, we only use ts js files so the package's js.map and d.ts files require loaders which causes the errors. I believe that's mostly our problem and requires further webpack updates.

But can't speak for salv0's case.

**Comment by ksvirkou-hubspot** [comment]
I ve fixed [the other related issue](https://github.com/HubSpot/hubspot-api-nodejs/issues/208).
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.3.2), please?
maybe it helps here
@salv0 @EugeneLuminaPain

**Comment by EugeneLuminaPain** [comment]
Thanks for the quick reply @ksvirkou-hubspot 

Unfortunately on our webpack build I'm still getting this parse error on mulitiple files.

`ERROR in ../shared/node_modules/@hubspot/api-client/lib/src/discovery/BaseDiscovery.d.ts 3:10
Module parse failed: Unexpected token (3:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`

I think in our case we'll have to extend the builder to cover these filetypes if I'm not mistaken.

**Comment by dgoemans** [comment]
I'm also having this on a project I just added 8.3.2 to, the API works great in dev (ts-node-dev@1.1.8, ts-node@3.3.0), but my builds (webpack@5.65.0) fail.

I've installed [ignore-loader](https://www.npmjs.com/package/ignore-loader) and added this to my webpack config (to ignore both the ts definitions and the js.map sourcemaps).
```
      {
        test: /\.js\.map$|\.d\.ts$/,
        loader: 'ignore-loader',
      },
```

Note that I saw in the other thread, someone mention using Typeorm, as am I. And Typeorm really does a number on your build process, so i wonder if this is related?

**Comment by danrimbault** [comment]
Is there any progress on this? We are also seeing build fails but able to run in development mode.

**Comment by ksvirkou-hubspot** [comment]
I've fixed it.
Could you check [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/8.4.1), please?

**Comment by gospag** [comment]
I tried the latest version, and I'm still getting the errors.

I'm in the same situation as OP, updated from 6.0.1-beta2 to 8.4.0 and now to 8.4.1

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
I've fixed it.
Could you check [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/8.4.2), please?
