### ISSUE TITLE
Submit Form data?

### ISSUE THREAD

**Issue by jziggas** [HubSpot/hubspot-api-nodejs#417]
https://legacydocs.hubspot.com/docs/methods/forms/submit_form

I don't see a method for submitting to forms anywhere. Is this a case of using `hubspotClient.apiRequest`  to use an [unwrapped endpoint](https://github.com/HubSpot/hubspot-api-nodejs#not-wrapped-endpoints)?

**Comment by ksvirkou-hubspot** [comment]
Hi @jziggas .
This SDK doesn't support legacy APIs at all.
We have [new version of Form API](https://developers.hubspot.com/docs/api/marketing/forms), it will be add to the SDK.

**Comment by devdudeio** [comment]
when this will be available in the sdk?

**Comment by ksvirkou-hubspot** [comment]
I've just investigated it deeper.
I am going to publish forms API to the SDK on next week.
But this API doesn't contain all necessary methods.
if there is no necessary method in the SDK use `hubspotClient.apiRequest`.
You can check all available SDK's methods in the [docs](https://developers.hubspot.com/docs/api/marketing/forms).

**Comment by ksvirkou-hubspot** [comment]
I've just published forms API in version [10.1.0](https://www.npmjs.com/package/@hubspot/api-client/v/10.1.0).

**Comment by jziggas** [comment]
Thanks!

**Comment by mbrowne** [comment]
This issue is not resolved and should be reopened IMO. There's still no way to submit data to an existing form other than `hubspotClient.apiRequest` or calling the legacy REST API directly.
